name: fastimage
description: Dart library that finds the size and type of an image given its uri by fetching as little as needed.
version: 2.0.0
homepage: https://github.com/ky1vstar/fastimage.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.6
