name: fastimage
description: A new Flutter package project.
version: 0.0.1
author: ky1vstar
homepage: https://github.com/ky1vstar/fastimage.dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: any