name: Dart CD

on:
  release:
    types:
        - created

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup credentials
      run: |
        mkdir -p ~/.pub-cache/
        echo ${{secrets.PUB_CREDENTIALS}} | base64 --decode > ~/.pub-cache/credentials.json
    - name: Release new version
      run: |
        pub publish -f
